SELECT * FROM [COVID PROJ]..[COVID DEATHS]
SELECT * FROM [COVID PROJ]..[COVID VACC]


SELECT CONTINENT,LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM  [COVID PROJ]..[COVID DEATHS]
ORDER BY 1,2


SELECT CONTINENT,LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
FROM  [COVID PROJ]..[COVID DEATHS]
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2

--TOTAL CASES VS TOTAL DEATHS
--PERCENTAGE OF DEATHS
SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (TOTAL_DEATHS/TOTAL_CASES)*100 AS DEATHPERCENTAGE
FROM [COVID PROJ]..[COVID DEATHS]
ORDER BY 1,2

--TOTAL CASES VS POPULATION
--PERCENTAGE OF POPULATION COVID POSITIVE 
SELECT LOCATION, DATE, TOTAL_CASES, POPULATION , (TOTAL_CASES/POPULATION)*100 AS PERCENT_OF_POPULATION_POSITIVE
FROM [COVID PROJ]..[COVID DEATHS]
ORDER BY 1,2

--FINDING COUNTRIES WITH HIGHEST PERCETAGE OF COVID
SELECT LOCATION,POPULATION, MAX(TOTAL_CASES) AS HIGHESTINFECTEDCOUNT, MAX((TOTAL_CASES/POPULATION)*100) AS PERCENT_OF_POPULATION_INFECTED
FROM [COVID PROJ]..[COVID DEATHS]
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION, POPULATION
ORDER BY PERCENT_OF_POPULATION_INFECTED DESC

--COUNTRIES WITH HIGHEST DEATH COUNT
SELECT CONTINENT, MAX(CAST(TOTAL_DEATHS AS INT)) AS HIGHESTTOTALDEATHS
FROM [COVID PROJ]..[COVID DEATHS]
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY HIGHESTTOTALDEATHS DESC


--TOTAL COUNTS GROUPING BY CONTINENT

SELECT LOCATION, MAX(CAST(TOTAL_DEATHS AS INT)) AS HIGHESTTOTALDEATHS
FROM [COVID PROJ]..[COVID DEATHS]
WHERE CONTINENT IS NULL
GROUP BY LOCATION
ORDER BY HIGHESTTOTALDEATHS DESC

--INCREASING CASES COUNT EACH DAY
SELECT DATE ,SUM(NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATH_PERCENTAGE
FROM [COVID PROJ]..[COVID DEATHS]
WHERE CONTINENT IS NOT NULL
GROUP BY DATE
ORDER BY 1,2

--TOTAL CASES TILL NOW
SELECT SUM(NEW_CASES) AS TOTAL_CASES, SUM(CAST(NEW_DEATHS AS INT)) AS TOTAL_DEATHS, SUM(CAST(NEW_DEATHS AS INT))/SUM(NEW_CASES)*100 AS DEATH_PERCENTAGE
FROM [COVID PROJ]..[COVID DEATHS]
WHERE CONTINENT IS NOT NULL
ORDER BY 1,2


--JOINING COVID DEATHS AND COVID VACC TABLES
SELECT * 
FROM [COVID PROJ]..[COVID DEATHS] AS DE
JOIN [COVID PROJ]..[COVID VACC] AS VA
ON DE.LOCATION=VA.LOCATION
AND DE.DATE = VA.DATE

-- NEW VACCINATIONS
SELECT DE.CONTINENT, DE.LOCATION, DE.DATE, DE.POPULATION, VA.NEW_VACCINATIONS
FROM [COVID PROJ]..[COVID DEATHS] AS DE
JOIN [COVID PROJ]..[COVID VACC] AS VA
ON DE.LOCATION = VA.LOCATION
AND DE.DATE = VA.DATE
WHERE DE.CONTINENT IS NOT NULL
ORDER BY 1

